### ISSUE TITLE
Pagination 

### ISSUE THREAD

**Issue by bidwolf** [bidwolf/advanced-css-animations#8]
### Description
This issue is related to adding pagination between sections and lessons

### Tasks
- [x] should be possible to navigate between sections
- [ ] should be possible to see an error page when the section doesn't exist
- [ ] should be possible to see mini  examples of each lesson in section root
- [x] should be possible to see a specific lesson on a particular page
